### ISSUE TITLE
Clicking pins in a shared sessions too quickly can make marks unclickable

### ISSUE THREAD

**Issue by Leappin** [pm-wobbuffet/scout#2]
We had two separate people run into this problem when trying this tool out, and I was unable to reproduce it for standard sessions so seems to be limited to sessions that have been shared. 

When cycling through the mobs too quickly it will lock one of the options out for everyone in the session. You can continue this until the map enters a state where no further marks can be added. 

A workaround exists where refreshing the page will reset the map for that user, and updates they push through are propagated without further issues. 

![chrome_1Bkj7eQlk5](https://github.com/pm-wobbuffet/scout/assets/102821798/2df3d9b5-1ac8-4a57-ac80-8e96fd2e7d4a)

**Comment by pm-wobbuffet** [comment]
Hey! Thanks for bringing it to my attention. I had some of these issues locally during development but it looks like I did not squash those bugs successfully. I apologize for the error. I'm still a bit into the DT launch window hype, but I'll try to do some debugging on it locally over the weekend.

**Comment by pm-wobbuffet** [comment]
From some local testing with the Adamantoise crew, it looks like it would specifically trigger when a user tried to update a zone that had a mark cleared by another user in a different session. This was because I was not properly clearing out the internal list of points that were already taken by mobs, so the local client had a "phantom" mob sitting on a point, which made it think there were no more valid mobs to be placed. Migrated the change into production today and will monitor. Let me know if you see further issues in other sessions with your crew.
Thanks for reporting, and happy hunting in DT!
